### ISSUE TITLE
Improve Telegram user displayname handling

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#11]
The displaynames we get from the Telegram client API may be affected by the user who we're puppeting. AFAIK if the puppeted user has set a custom displayname for the target user, there's no way to get the real displayname that the target user has set themselves.

**Comment by jcgruenhage** [comment]
This is problematic if multiple people share a bridge and one person doesn't have a name set. It would be great to at least let the bridge admin set a preference, prefer display names read by telegram user x for example.

**Comment by tulir** [comment]
The remaining changes aren't as important, 1f5261ff8fb53307ec20b2a88427e50ce1783a02 solved the primary problem

**Comment by tulir** [comment]
I don't remember what the remaining changes are anymore, so I guess I'll open a new issue if I remember them again.
