### ISSUE TITLE
telethon-aio instead of telethon-aio-git with Python 3.5.5 on Ubuntu 16.04

### ISSUE THREAD

**Issue by jooize** [tulir/mautrix-telegram#110]
https://github.com/tulir/mautrix-telegram/blob/4804023acfae4cc7e1604038c22a06c64d1c61d3/setup.py#L36

**Comment by tulir** [comment]
`telethon-aio` doesn't work with Python 3.5, since it uses some 3.6-specific asyncio stuff. If `--process-dependency-links` doesn't work for some reason, you can install `https://github.com/tulir/telethon-asyncio/tarball/master#egg=telethon-aio-git` manually.
