### ISSUE TITLE
Telematrix import script

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#112]
Some migration path from [telematrix](https://github.com/SijmenSchoon/telematrix) could be useful.

**Comment by tulir** [comment]
Most of the models seem easy enough to migrate. Sample data would be nice to figure out the exact format, I'm guessing some data conversion will be needed from the bot API format to client API format.

Also, looks like telematrix uses sqlalchemy too: https://github.com/SijmenSchoon/telematrix/blob/master/telematrix/database.py

**Comment by turt2live** [comment]
Sample database: https://t2bot.io/_matrix/media/v1/download/t2l.io/2914bcf62f3e5facd3998eaaa31b3091

It's from my development environment and has very little data in it though.
