### ISSUE TITLE
Backfill messages from Telegram missed during downtime

### ISSUE THREAD

**Issue by jcgruenhage** [tulir/mautrix-telegram#124]
When the bridge was down, it should try to catch up on the messages it had missed instead of just continuing at the point where it came back online.

**Comment by tulir** [comment]
Might require support from Telethon.

Somewhat related to #99.

**Comment by Lonami** [comment]
See https://github.com/LonamiWebs/Telethon/issues/746.

**Comment by tulir** [comment]
I guess the bridge side of this is done. The bugginess is in Telethon, so nothing can be done here.

**Comment by Lonami** [comment]
After some talking with other developers seems like `getDifference`, which is what `.catch_up` does, is *not* the right way to get missed updates. You see, clients like Telegram Desktop don't even save messages to a file, and on startup they get dialogs and load messages only when you click a chat, so it really depends on the use-case. Not sure about `.catch_up`'s future :thinking:
