### ISSUE TITLE
Add command to check telegram connection status

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-telegram#14]
Will be good to have command for check current connection status to telegram (logged out, logged in and active, logged in and inactive / connection problem), something like `ping`, that send some basic api command, wait reply and report status.

**Comment by tulir** [comment]
A basic ping command shouldn't be too hard, but telegram-mtproto doesn't properly throw errors, so it's hard to differentiate between different inactive states (logged out, connection problem, server salt problem, etc..).

**Comment by MurzNN** [comment]
Maybe we can do all checks via simply sending `help` command to botfather and check correct reply?

**Comment by tulir** [comment]
The ping command I added in eaff820 calls `contacts.getContacts` with a 2.5s timeout to determine if the connection is working. I don't think messaging a bot will help, since it won't give more specific errors. The problem is in telegram-mtproto, so we'll just have to wait for that to get fixed.
