### ISSUE TITLE
Cannot bridge to a room with 2+ people in it

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#147]
When a matrix room has more than 2 people in it (you, the bot, and someone else) the bridge is silent and doesn't bridge to Telegram. Kicking the third person and repeating the bridge command will have the bridge respond.

**Comment by tulir** [comment]
Did you remember to use the command prefix? The bridge allows unprefixed commands only in rooms with exactly two members: you and the bot.

[Management commands](https://github.com/tulir/mautrix-telegram/wiki/Management-commands):
> If the room you send the command to does not have users other than you and the bridge bot, you do not have to prefix commands, i.e. you can literally write help to get the help message. **If the room has more users, you must use the command prefix (`!tg` by default). For example: `!tg help`**. The command prefix is always allowed even if it's not required.

**Comment by turt2live** [comment]
I should probably read the instructions ._.
