### ISSUE TITLE
Use /joined_members instead of /members

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#181]
`/members` is *really* hard on the server while `/joined_members` is easier to calculate. Spec: https://matrix.org/docs/spec/client_server/unstable.html#get-matrix-client-r0-rooms-roomid-joined-members

**Comment by tulir** [comment]
I thought I also used it for getting invited users, but that doesn't seem to be the case. Anyway, moved to tulir/mautrix-appservice-python#5
