### ISSUE TITLE
Need to change power level event after inviting the bridge to the room for the first time

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#182]
The bridge doesn't appear to cache/lookup the current power levels when it first joins. This causes confusion when admins of the room are told they don't have permission to bridge chats. 

The workaround is to change the power level of anyone, or change a setting that modifies the power level event. The bridge picks this up and then the room can be bridged.

**Comment by tulir** [comment]
It should try to look up the power levels, but it's very possible I've missed something since I usually test it as bridge admin.

**Comment by turt2live** [comment]
Fixed by referenced commits.
