### ISSUE TITLE
Option to disable the bridge bot's profile doesn't work

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#184]
If left as an empty string, the config migrator overwrites the values.

**Comment by tulir** [comment]
Did you leave it empty
```yaml
foo:
```
or set it to an empty string?
```yaml
foo: ''
```

Only the second method works, maybe the comment should be clearer about that

**Comment by tulir** [comment]
Works fine for me. It changes `""` to `''` and it doesn't touch `''`.

**Comment by turt2live** [comment]
Alright, I guess I'll close this then. It was probably my fault for doing it wrong at some point, but I don't want to risk trying it again (given the thousand or so room the bridge is in).
