### ISSUE TITLE
Python 3.6 syntax

### ISSUE THREAD

**Issue by Raven24** [tulir/mautrix-telegram#189]
https://github.com/tulir/mautrix-telegram/blob/340360e6a0582fafdd8f98022af743eca65897e1/alembic/versions/6ca3d74d51e4_move_state_store_to_main_database.py#L96
This syntax is only available since Python 3.6, so you'd have to increase the required version in the Wiki documentation or change this to an older syntax.
There also seems to be a backport package: https://stackoverflow.com/a/49963231

**Comment by tulir** [comment]
I use f-strings everywhere with a [real backport](https://github.com/asottile/future-fstrings), but I haven't enabled it in any of the alembic migrations.
