### ISSUE TITLE
Option to disable matrix puppeting 

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#199]
I'm gearing up towards having puppeting enabled on my instance, although having access tokens to user accounts is way too much power. Eventually when matrix supports oauth (or similar), it'd be nice if the bridge supported that.

For now though, it'd be nice to be able to disable matrix puppeting.

**Comment by tulir** [comment]
Matrix puppeting currently requires logging in with a Telegram account first, so I guess the best solution is to add a new permission level before "full" that doesn't allow Matrix puppeting.
