### ISSUE TITLE
Emotes don't work (anymore)

### ISSUE THREAD

**Issue by xx4h** [tulir/mautrix-telegram#200]
1. Do `/me is alive`
2. It won't get bridged

Looks like there is something going wrong in [mautrix_telegram/mautrix_telegram/formatter/from_matrix/\_\_init\_\_.py:84](https://github.com/tulir/mautrix-telegram/blob/f2390c493786dbeb9c3c369af2b8ce784d6ea250/mautrix_telegram/formatter/from_matrix/__init__.py#L84)

`'NoneType' object has no attribute 'offset'`

But i wasn't able to get the full traceback.

**Comment by tulir** [comment]
Apparently this isn't broken anymore
