### ISSUE TITLE
Being in a matrix room bridged to Telegram then enabling puppeting doesn't bridge you if you didn't join the Telegram side

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#205]
1. Join a matrix room that is bridged to Telegram
2. Don't be in the Telegram room
3. Puppet your Telegram account
4. Speak in the matrix room - messages will not be bridged

**Comment by tulir** [comment]
Three potential solutions:
* Make the Telegram user join the Telegram chats (potentially unwanted, not always possible)
* Kick the Matrix user from the portals if they're not in the respective Telegram chat
* Use the same portal list that is used for users who logged in with a bot (potentially unreliable, but should work fairly well for real users. Probably the best solution)

**Comment by turt2live** [comment]
or a 4th option: use the relaybot (if configured) as a fallback

**Comment by tulir** [comment]
This should be fixed in f8e429f08a169bf9efef6cf135a69cc94d9e7358 (option 3)
