### ISSUE TITLE
Appservice bot not joining private chats

### ISSUE THREAD

**Issue by EorlBruder** [tulir/mautrix-telegram#207]
Mautrix is running without any errors in the logs (docker, latest, connected to postgres). 

When I try to write to the appservice bot it won't join the room created by "Start chat" and searching for the bot, it just stays as invited. There isn't any sign of this action in the logs. That way I can't really use this bridge, as I am missing the ability to connect my accounts.

**Comment by icewind1991** [comment]
I had the same issue,

it was caused by the url of the bridge not being set correctly in the registration.yml
