### ISSUE TITLE
database: triple slash

### ISSUE THREAD

**Issue by whoamin** [tulir/mautrix-telegram#208]
triple slash not work for me, you should fix it in config example and wiki pages
not work:
postgres:///user:password@localhost/mautrixtelegram
work:
postgres://user:password@localhost/mautrixtelegram

**Comment by tulir** [comment]
As far as I can tell, only the [DBMS migration](https://github.com/tulir/mautrix-telegram/wiki/Database-management-system-migration) wiki page actually had a `postgres:///` example. The base format is something like `protocol://auth@host/dbname`, but SQLite doesn't have auth or host, so it's always `sqlite:///filename`.

Anyway, I added the format for postgres and sqlite to the database config comment.
