### ISSUE TITLE
Portal room created before user has chance to manually create a bridge

### ISSUE THREAD

**Issue by olymk2** [tulir/mautrix-telegram#219]
That Telegram chat already has a portal at !randomid:t2bot.io. Additionally, you do not have the permissions to unbridge that room.

I am an admin so cant get any more permissions, !tg unbridge gives me the same error and I can't create a bridge because I get the above error.

Whats the process to completely unlink so I can start again fresh ?

**Comment by tulir** [comment]
There's some new bug where the bridge creates portals too soon (when the bot joins the telegram chat probably). You can invite [TravisR](https://matrix.to/#/@travis:t2l.io) to the room to get it fixed (also maybe join [#help:t2bot.io](https://matrix.to/#/#help:t2bot.io)).

**Comment by tulir** [comment]
I think this is fixed now
