### ISSUE TITLE
Warn the user more on the implications of logging in

### ISSUE THREAD

**Issue by Mikaela** [tulir/mautrix-telegram#248]
I am worried about the homeserver getting all access to Telegram message history and the ability of sending messages as the user. I understood that currently there is only warning on Telegram side of not giving the code anyone else.

Another thing I worry about is that while I can decide whether or not I trust a public provider with my credentials of another service, how do I know if my Telegram contacts are using Telemautrix and thus sending private discussions that I am trusting to Telegram also to some Matrix homeserver? There is nothing illegal being done at least with Finnish laws, but I am not sure how ethical this is.

I am opening this issue based on discussion at Matrix and https://github.com/t2bot/t2bot.io/issues/15.

**Comment by Mikaela** [comment]
How are redactions handled? If e.g. naked selfies were exchanged on Telegram and removed there, would they also be automatically removed from Matrix side? Or are they only hidden from view and still stored forever somewhere in Synapse?

https://github.com/matrix-org/synapse/issues/1287 & https://github.com/matrix-org/synapse/issues/2369 hint to me that they are stored forever without warning?

What if it was illegal content?

**Comment by Extarys** [comment]
from what I understand, files uploaded and stored on a marix server stays there indefinitely, even if the message is deleted on the matrix/riot side.

![image](https://user-images.githubusercontent.com/11581433/50070362-a61d2f80-019b-11e9-8073-332e335eb7fb.png)

**Comment by tulir** [comment]
> How are redactions handled?

The bridge redacts the messages on Matrix, after which it's up to the Matrix server.
