### ISSUE TITLE
A database error prevents all future database interactions from working

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#263]
if there's something like "duplicate key for table portals" the bridge should still work for every other interaction with the database.

If this the database error is unrecoverable, prefer crashing.

**Comment by tulir** [comment]
I'm going to reduce ORM usage which should make it be less stuck after a failing transaction. It should also be easier to avoid invalid transactions with SQLAlchemy Core since there I can actually see what I'm doing in the database.
