### ISSUE TITLE
Bridge doesn't re-invite you to portals after logging out and back in to your Telegram account

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#278]
Empirically, at least. As far as I can tell, the bridge did the right thing when someone bridged their account for the first time (it invited them to the room, and they joined). Later, they logged out and the bridge rightfully kicked them from the room. Some time later, they logged back in again and the bridge didn't even try to invite them to the room, which is not what is expected.

**Comment by JonTheNiceGuy** [comment]
I'm the user in question. Any interaction from my side required on @turt2live 's bridge, let me know and I'll do it :)

**Comment by tulir** [comment]
Is it not reinviting even when something happens in the chat?

**Comment by turt2live** [comment]
Nope
