### ISSUE TITLE
Logout fails

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-telegram#286]
Hi,
i am using the latest release v0.5.0-rc3 and have a problem with logout:

![grafik](https://user-images.githubusercontent.com/5631071/53441138-6b8b0b00-3a06-11e9-8eec-afc1ea96d2db.png)

![grafik](https://user-images.githubusercontent.com/5631071/53441168-79d92700-3a06-11e9-8a0e-3e3525bd51a3.png)

problem occured in previous version 0.40 too

Anyone an idea how to fix it? I think it happened because i messed around with https://github.com/turt2live/matrix-dimension integration before.

**Comment by vmario89** [comment]
seems that other commands do not work too:
![grafik](https://user-images.githubusercontent.com/5631071/53442361-709d8980-3a09-11e9-95ed-5a7602817f26.png)

**Comment by tulir** [comment]
Those are three unrelated issues. The first two should be fixed now, the third is a known issue where I haven't pinned down the actual problem yet.
