### ISSUE TITLE
Recorded audio from Telegram is not recognized on Android 6.0.1

### ISSUE THREAD

**Issue by markuskramerIgitt** [tulir/mautrix-telegram#288]
When you record and send audio (hold the microphone icon at the bottom right corner) in Telegram, the bridge sends a file named "Uploaded file" ("mimetype": "audio/ogg") to Riot
When you try to open this file, Android alerts "This format isn't supported or the file is corrupted".

Appending .ogg to the file name results in the same error message.

Because another .ogg audio file plays fine, I assume the audio encoding is an issue.

Can I try something more?

**Comment by markuskramerIgitt** [comment]
Riot on Windows plays the audio.
So this is not an issue with the Format (which is Ogg Opus).
Android should be able to play Ogg Opus.

**Comment by markuskramerIgitt** [comment]
Running `opusinfo` (from https://opus-codec.org/downloads/) on the file, the output ends with 
```
WARNING: illegally placed page(s) for logical stream 1
This indicates a corrupt Ogg file: Page found for stream after EOS flag.
```

While Riot on Windows and VLC still play the file, this could be the reason why Android does not.
So it seems to be an issue with the format, after all.

I assume neither the bridge nor Matrix (re)encodes the audio, so Telegram is responsible for the encoding.

Correct?

**Comment by markuskramerIgitt** [comment]
The audio recording saved to file from Telegram shows the same warning as above.

A second audio recording saved to file from Telegram does not show the warning, but it does not appear in Riot (after 1 hour).

**Comment by tulir** [comment]
Yeah, I guess this is a telegram or riot android problem, probably should be fixed in android.
