### ISSUE TITLE
Telethon 1.6 support

### ISSUE THREAD

**Issue by nyanloutre** [tulir/mautrix-telegram#295]
A new version of Telethon is out with several bugfixes: https://telethon.readthedocs.io/en/latest/extra/changelog.html#tidying-up-internals-v1-6

If the breaking changes don't break mautrix this version should maybe be allowed in the setup.py

**Comment by tulir** [comment]
Seems to work fine with no changes. setup.py updated in 7c46bf4b9eb0e92973a16e0e1c1ec71a3e52cacc
