### ISSUE TITLE
Example for public web server page

### ISSUE THREAD

**Issue by vmario89** [tulir/mautrix-telegram#298]
Hi,
in configuration there is an endpoint facing to public:
![grafik](https://user-images.githubusercontent.com/5631071/54374850-4510d500-4680-11e9-9f57-279f7460936d.png)

can you tell me on how to configure this? do i need to reverse proxy it to a location like matrix.domain.tld/telegram by pointing to http://127.0.0.1:8070 ?

regards, Mario

**Comment by tulir** [comment]
The public things are served under the given prefix on the listener specified with the `hostname` and `port` in the `appservice` section. You can have something like a reverse proxy targeting that and then set `external` to what users can use to reach that proxy.
