### ISSUE TITLE
!tg pm doesn't invite the sender to the room with the private chat

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#305]
I think this is because https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/portal.py#L346 is nested one step too far, making the invite call never happen.

**Comment by tulir** [comment]
I haven't been able to reproduce this. `pm` with no portal existing works fine, leaving deletes the portal as expected and `pm` even re-invites the user if I comment out the delete-on-leave code and then leave.
