### ISSUE TITLE
"login" fails with internal server error

### ISSUE THREAD

**Issue by olmari** [tulir/mautrix-telegram#314]
0.5.1 version fails when new user tries to login command with bot and then use weblogin. Affects all new users trying to use it.

As attachments there are mautrix-telegram log and then our config.yaml for mautrix-telegram.

[mautrix-telegram.log](https://github.com/tulir/mautrix-telegram/files/3090721/mautrix-telegram.log)
[config.yaml.log](https://github.com/tulir/mautrix-telegram/files/3090724/config.yaml.log)

**Comment by tulir** [comment]
Looks like this was already fixed two days before v0.5.1 in tulir/telethon-session-sqlalchemy@cc341dbad2740b40a8ddff84533f34ab77cf3add and tulir/telethon-session-sqlalchemy@af2f2c5ef0f99ac35451bfdb08b7ff91a8a14fab, but the minimum telethon-session-sqlalchemy version hadn't been bumped to 0.2.14. The code in the traceback shows it's the broken 0.2.12 code.
