### ISSUE TITLE
No Notifications from Bots

### ISSUE THREAD

**Issue by failx1993** [tulir/mautrix-telegram#318]
Hello guys,

i am using a Telegram Bot for sending me updates from my home automation system. 
I noticed that i get the message but no notification or something else. Only thing that changes is that the Chat is written in Bold letters but no message indication or notification on Riot PC App nor mobile app. If you tell me what things you need i can provide it.

**Comment by tulir** [comment]
Notifications are up to your client, not the bridge. Riot Web at least has a "Messages sent by bot" row in the notification settings:
![image](https://user-images.githubusercontent.com/4224639/57070529-6ab17680-6ce0-11e9-9650-c39909bf72c5.png)

If you don't want them to be sent as `m.notice`s, you can change the [`bridge.bot_messages_as_notices`](https://github.com/tulir/mautrix-telegram/blob/master/example-config.yaml#L150-L151) config field (or the corresponding per-room config with the `!tg config` command)
