### ISSUE TITLE
Don't log private information by default

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#321]
Logs currently contain message content and other private information. The logs should be minimized to contain as little private information as possible without reducing usefulness when debugging.

**Comment by joepie91** [comment]
This should probably have at least a rudimentary version (eg. "enable/disable message logs" option) implemented sooner rather than later?

It's... not great that bridge administrators are immediately confronted with private conversations whenever they look at the logs.

**Comment by tulir** [comment]
> This should probably have at least a rudimentary version

https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/example-config.yaml#L426

**Comment by joepie91** [comment]
Ah, right. In that case: the default/example should probably be changed *not* to accumulate private messages in the logs by default?

(Also, what level is required to stop private message logging?)

**Comment by Bubu** [comment]
I still get message content on DEBUG log lovel.

```
Jul 04 20:38:48 bubu mautrix-telegram[50669]: [2020-07-04 20:38:48,275] [DEBUG@mau.portal.235712154] Sending <messageContent> to !roomid:bubu1.eu by @telegramuser:bubu1.eu
