### ISSUE TITLE
sending "m.relates_to": null causing internal server error in Synapse

### ISSUE THREAD

**Issue by Limvot** [tulir/mautrix-telegram#336]
Not sure if this bug is more for Synapse or mautrix-telegram, but when I upgraded both today Telegram messeges stopped appearing in Matrix.

It sends messages like:
`[2019-06-15 21:32:07,871] [DEBUG@mau.as.api] PUT /rooms/%21mMWGhycXzeDvpkjCzk%3Aroom409.xyz/send/m.room.message/61560634327871 {"body": "Forever", "msgtype": "m.text", "m.relates_to": null, "external_url": "https://t.me/c
/1050980458/48908"} as user @telegram_163061100:room409.xyz`

causing

`mautrix_appservice.errors.MatrixRequestError: 500: {"errcode":"M_UNKNOWN","error":"Internal server error"}`

On the synapse side `                                       File "/nix/store/n55kpxsc5m225xdvyqg3p0kljksfyyyx-matrix-synapse-1.0.0/lib/python3.7/site-packages/synapse/handlers/message.py", line 611, in create_new_client_event
                                         if relation.get("rel_type") == RelationTypes.ANNOTATION:
                                     AttributeError: 'NoneType' object has no attribute 'get'`

(These are actually from different messages, because different logs, but this is what happens every time)

Let me know if I should report to Synapse instead, or if I messed up somewhere. Thank you!

**Comment by tulir** [comment]
It's a bug in synapse, but it's fixed in the bridge in both the latest patch release (0.5.2) and on master (0.6.0 dev)

**Comment by WGH-** [comment]
What bug? Is there an issue open in Synapse GitHub?
