### ISSUE TITLE
Messages created by me (in Telegram) are not synced to matrix

### ISSUE THREAD

**Issue by toger5** [tulir/mautrix-telegram#339]
I am using the bot.
When i write a message in a direct chat (in telegram), my own message does not get synced to matrix.
If i write in matrix, it will also be in telegram.

**Comment by olmari** [comment]
This way of chatting will only work if you use double puppeting aka in-matrix method, see https://github.com/tulir/mautrix-telegram/wiki/Authentication

**Comment by tulir** [comment]
What @olmari said. I'm currently not planning on supporting it without that.

**Comment by toger5** [comment]
Oh okay, is that even possible witht the bot?

**Comment by olmari** [comment]
Umm, yes? Just like I said in the previous message...
