### ISSUE TITLE
consider changing default port

### ISSUE THREAD

**Issue by swedneck** [tulir/mautrix-telegram#345]
The current default port 8080 can conflict with the IPFS gateway port and i believe also the syncthing web UI port, it would be good to change this to some other port number.

**Comment by tulir** [comment]
8080 is a standard alternate HTTP port, of course it has "conflicts". However, I do have my [own port numbering scheme](https://cloud.maunium.net/index.php/s/rR5kRgasLT3MniZ) and I'm not quite sure why I didn't use that for bridges too...
