### ISSUE TITLE
Bridge don't delete messages, deleted on Telegram side by bots

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-telegram#347]
Some Telegram rooms use Telegram bots for auto-remove spam messages. But when telegram bot remove message on Telegram side, this event is not bridged to Matrix side, so on Matrix room this message stays visible.

Is it possible to intercept and bridge those delete message events to Matrix side?

**Comment by olmari** [comment]
Does the matrix-bot have permissions to delete messages on both matrix and telegram?

**Comment by tulir** [comment]
Sometimes telegram doesn't feel like telling the bridge that a message was deleted. I'm pretty sure bot deletions aren't any different from normal deletions and are handled just fine

**Comment by MurzNN** [comment]
Yes, strange, but in problematic rooms bot have zero permission, seems those rooms are created via too old Telegram bridge?.. Now I give to bot admin permissions and seems deletions bridged normally

**Comment by tulir** [comment]
> in problematic rooms bot have zero permission, seems those rooms are created via too old Telegram bridge?

They probably weren't created by the bridge
