### ISSUE TITLE
Inconsistent string interpolation between alembic and mautrix-telegram

### ISSUE THREAD

**Issue by serra-allgood** [tulir/mautrix-telegram#362]
The password I generated for a telegram postgres role just happened to have a `%` character in it. I'm assuming`alembic` uses the old sprintf interpolation syntax because trying to setup the db caused it to throw an error complaining about invalid string interpolation. I was able to work around it by escaping it as `%%`, but then when starting the bridge, the bridge was unable to auth to postgres because of the extra character. A minor bug, but I felt it worth opening the issue.

**Comment by tulir** [comment]
Yeah, looks like the URI is passed to alembic through its config thing, which supports variable interpolation.
