### ISSUE TITLE
Uploads to Telegram are turning up as "matrix_uploadNone"

### ISSUE THREAD

**Issue by Half-Shot** [tulir/mautrix-telegram#376]
The file in question is a .gcode file. Can be found at: https://matrix.half-shot.uk/_matrix/media/r0/download/half-shot.uk/476b861d11c418a29e30a4b5992169753697aef5

```
{
  "content": {
    "body": "dogtag.gcode",
    "info": {
      "mimetype": "text/x.gcode",
      "size": 42963
    },
    "msgtype": "m.file",
    "url": "mxc://half-shot.uk/476b861d11c418a29e30a4b5992169753697aef5"
  },
  "origin_server_ts": 1572558277412,
  "sender": "@Half-Shot:half-shot.uk",
  "type": "m.room.message",
  "unsigned": {
    "age": 1187,
    "transaction_id": "m1572558277263.384"
  },
  "event_id": "$JJPjoJRUZiLeF--PulfxAn7zCHVNhowGr3rnesFMc4M",
  "room_id": "!BxtwhBeTBeKpPsUVba:half-shot.uk"
}
```

**Comment by tulir** [comment]
This was a bug/feature until very recently: it tried to intelligently use the body as either caption or filename depending on extension. I dropped the caption stuff and added a `!tg caption` command until Matrix gets proper captions
