### ISSUE TITLE
Creating Telegram chat fails if room has another non-encountered Telegram user

### ISSUE THREAD

**Issue by jaywink** [tulir/mautrix-telegram#379]
Trying to create a portal from Matrix side with `!tg create` - fails with:

```
Could not find the input entity for <telethon.tl.types.PeerUser object at 0x7ff7075ce8d0>. Please read https://docs.telethon.dev/en/latest/concepts/entities.html to find out more details.
```

Running on `latest` docker tag (:sweat_smile:), tag ID 210786a3d.

Can't see anything super interesting in the logs regarding this.

**Comment by tulir** [comment]
I'm guessing this happens if you have some logged in telegram user in the room who you haven't encountered in a telegram
