### ISSUE TITLE
Web login configuration

### ISSUE THREAD

**Issue by coderzstas** [tulir/mautrix-telegram#381]
Is any weblogin configuration guide ? i configured config.xml , added my domain name to 

>     # Public part of web server for out-of-Matrix interaction with the bridge.
    # Used for things like login if the user wants to make sure the 2FA password isn't stored in
    # the HS database.
    public:
        # Whether or not the public-facing endpoints should be enabled.
        enabled: true
        # The prefix to use in the public-facing endpoints.
        prefix: /public
        # The base URL where the public-facing endpoints are available. The prefix is not added
        # implicitly.
        external: https://<editedforprivacy>/public

but when trying to login getting 

> No Such Resource
No such child resource.

**Comment by coderzstas** [comment]
solved :)

**Comment by hafx** [comment]
Hi, 
Is it possible to know how you solved this ?

Thanks

**Comment by bolsunovskyi** [comment]
Same question.

**Comment by lfom** [comment]
@hafx @bolsunovskyi 

check #298 

I got it working after adding a reverse proxy for my `nginx` conf for the Matrix HS:

```
        location /public {
                proxy_pass http://HOSTNAME:PORT;
        }

```
