### ISSUE TITLE
Bugs when connecting to new account

### ISSUE THREAD

**Issue by Flakebi** [tulir/mautrix-telegram#39]
Hi,
thanks for this awesome bridge.
So far it works really well for me, I just had some problems when initially logging in:

1. The `enter_code` command was not found (neither directly nor by `login`), renaming it to `entercode` worked.
2. The second problem was, that `args[0]` in [mautrix_telegram/commands.py#L133](https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/commands.py#L133) contained only a space so something is wrong there.

**Comment by tulir** [comment]
It seems that the internal improvements to command handling in 4593e1c857f89a5ddd3aa76e733a4fb737c81ea2 broke logging in and unknown command handling.
