### ISSUE TITLE
Don't print stack traces to end users

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#392]
eg: https://matrix.to/#/!mPYrVomQESEYWWudQw:matrix.org/$157530231150533RueeT:matrix.org?via=t2bot.io&via=matrix.org&via=privacytools.io

**Comment by tulir** [comment]
Looks like I forgot to override the [relevant property](https://github.com/tulir/mautrix-python/blob/master/mautrix/bridge/commands/handler.py#L104-L113) in https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/commands/handler.py
