### ISSUE TITLE
install error on debian

### ISSUE THREAD

**Issue by bendschs** [tulir/mautrix-telegram#396]
on my system (debian armv7, python 3.5.3 (latest official release) i get the following error while trying to install v0.7.0-rc2. Last official realease is working and running.
 
`Collecting mautrix-telegram[all]   Downloading https://github.com/tulir/mautrix-telegram/tarball/master      \ 430kB 311kB/s     ERROR: Command errored out with exit status 1:      command: /home/osmc/A/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-de4md89z/mautrix-telegram/setup.py'"'"'; __file__='"'"'/tmp/pip-install-de4md89z/mautrix-telegram/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-de4md89z/mautrix-telegram/pip-egg-info          cwd: /tmp/pip-install-de4md89z/mautrix-telegram/     Complete output (6 lines):     Traceback (most recent call last):       File "<string>", line 1, in <module>       File "/tmp/pip-install-de4md89z/mautrix-telegram/setup.py", line 27         """)           ^     SyntaxError: invalid syntax     ---------------------------------------- ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by tulir** [comment]
v0.7.0 no longer supports Python 3.5

**Comment by bendschs** [comment]
what is the lowest version of python still supported?

**Comment by tulir** [comment]
3.6, although 3.7 is recommended

**Comment by bendschs** [comment]
thank you for the quick answer!
