### ISSUE TITLE
Re-invite Matrix user to old Telegram private chats rooms after logout-login

### ISSUE THREAD

**Issue by MurzNN** [tulir/mautrix-telegram#397]
After `logout` in Telegram bridge - he kick me from all Telegram bridged rooms. After logging back va `login` - he re-invite me to old Telegram group chat rooms, but not to old private chats rooms.

And even if I receive new messages from Telegram users in private chats after relogin - he not re-invite me to old rooms, and not create new rooms, so I receive no notifications about new direct messages to me on Matrix side! I can see new messages only from Telegram native clients.

Via `pm <user phone>` command I can manually re-invite me to needed contact rooms, this command will re-invite me to old room, where I see all old history, but in that room there are missed history part between logout-login time.

So after this "fix" I can normally receive new private messages from manually "fixed" Telegram users, but not for all other.

Can you please fix this problem and re-invite user to all old rooms with direct Telegram chats after logout-login? If not automatically, maybe via some command like `!tg sync private-chats`. If this is not possible, can you please describe reasons?

**Comment by JuniorJPDJ** [comment]
Bug is fixed but you anyway need to remove every bridged chats for your existing DMs to make it rebridge it for you.
I just logged off, removed connection from bridge db, left all chats with `(Telegram)` in name and i got reinvited to newly created rooms.
SQL i needed to run on mautrix db to remove connections between direct chats in matrix and telegram:
`DELETE FROM portal WHERE tg_receiver=YOUR_TG_ID and peer_type='user';`
