### ISSUE TITLE
webp -error 0.7.0 rc2

### ISSUE THREAD

**Issue by bendschs** [tulir/mautrix-telegram#398]
With the newest version 0.7.0 rc2, i get the following error when someone is sending me stickers.
mautrix-telegram install was successfully with pip running on debian (stretch).

```
[2019-12-09 11:33:31,098] [WARNING@py.warnings] /opt/synapse/lib/python3.7/site-packages/PIL/Image.py:2817: UserWarning: image file could not be identified because WEBP support not installed
  warnings.warn(message)
```

**Comment by tulir** [comment]
I think you might need `libwebp` installed before installing Pillow with pip. You can try `pip uninstall pillow`, `sudo apt install libwebp6 libwebp-dev`, `pip install pillow`

**Comment by bendschs** [comment]
thanx, that was it ... it's working now.

**Comment by tulir** [comment]
Added note to https://github.com/tulir/mautrix-telegram/wiki/Optional-dependencies

Might need to make the native deps more prominent somehow, but it's fine for now
