### ISSUE TITLE
Support logging in with QR code

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#399]
~~Upcoming Telegram feature: https://t.me/tgbeta/3884. Usually features announced there don't take too long to arrive, so should be ready for 0.8.0~~ https://core.telegram.org/api/qr-login

**Comment by tulir** [comment]
This requires some changes in Telethon, so I'll probably just wait for there to be a friendly method for this: LonamiWebs/Telethon#1471

**Comment by Lonami** [comment]
https://github.com/LonamiWebs/Telethon/commit/c904b7ccd8a1dbc185bb614df51ebb124de109bd is now fixed on my side. Showing the QR code is up to you.
