### ISSUE TITLE
Add option to have a bot relay messages for non-authenticated Matrix users

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#4]
Having a bot would make getting started with the bridge easier, as users wouldn't have to log in with their Telegram account right away. It could also potentially help with message duplication problems.

**Comment by MurzNN** [comment]
This will be very useful feature for implement replacement of [telematrix](https://github.com/SijmenSchoon/telematrix) Telegram<>Matrix bot based bridge, that not so actively maintained.
