### ISSUE TITLE
Option to encrypt content from telegram

### ISSUE THREAD

**Issue by IF-Adin** [tulir/mautrix-telegram#403]
Hi,
i was wondering how difficult it would be to make the bot encrypt content it receives from telegram.

The problem is that i have no control over what people receive and it all gets saved on my server. I'd certainly feel better if it was all just encrypted and accessible only to those who are verified.

**Comment by tulir** [comment]
It's essentially impossible currently, but it might happen eventually

**Comment by IF-Adin** [comment]
Is that because the bot has no device that can be verified?

**Comment by tulir** [comment]
This is now possible on master. https://github.com/tulir/mautrix-telegram/wiki/End‐to‐bridge-encryption
