### ISSUE TITLE
Add option to ignore specific Telegram chats in automatic portal creation

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#41]
* [ ] Change `!delete-portal` so that the portal wont be recreated before a restart
* [ ] Add a command to un-flag portals from being exempt from room creation
* [ ] Add option to `!delete-portal` and `!unbridge` to make the no-recreate flag persistent
* [ ] (Maybe) Add option to un-flag command or a separate command to normally create a portal room (without receiving message)

**Comment by f0x52** [comment]
I'd like a whitelist too, bridging only a specific few chats
