### ISSUE TITLE
Command to disable bridging of join/leave messages in relay bridged rooms

### ISSUE THREAD

**Issue by homebeach** [tulir/mautrix-telegram#410]
It would be a good feature to have command that would disable bridging of join/leave messages when using relay bridging. Relay bridged Telegram groups are often filled with join/leave spam from IRC and Matrix.

**Comment by tulir** [comment]
```
!tg config set state_event_formats join: ''
leave: ''
name_change: ''
```

**Comment by homebeach** [comment]
Yes but what if you are using a public bridge with no access to admin features?

**Comment by homebeach** [comment]
I mean to have configurations per bridged room that could be controlled by room admins. Some rooms bridged with same bridge could relay joins and quits and some rooms not.
