### ISSUE TITLE
Voice messages are sent as m.file instead of m.audio

### ISSUE THREAD

**Issue by n0emis** [tulir/mautrix-telegram#419]
When receiving voice-messeages from telegram, they are send to matrix as a file without an extension.

They seem to be opus-files, see `ffprobe`s output below:
```
Input #0, ogg, from 'MEZZErJAnPTbnMPCyrddChlW':
  Duration: 00:00:02.79, start: 0.000000, bitrate: 19 kb/s
    Stream #0:0: Audio: opus, 48000 Hz, mono, fltp
```

It would be nice it `.ogg` would be appended to such files, so that riot-web could be able to show the audio-player.

**Comment by thesseyren** [comment]
Hello, I'm sorry because I couldn't reproduce the issue that you have.
Yes sound files comes without an extension, but my Riot can play these files with audio-player.
My Riot desktop version is 1.5.8 and it was installed with debian package.

**Comment by n0emis** [comment]
@thesseyren Mhh, neither RiotX, Riot-Web nor Riot-Android detect it on my side. By simply adding `.ogg` to the filename they do.

**Comment by tulir** [comment]
If the msgtype and mime type are correct, then it's really a client bug

**Comment by n0emis** [comment]
> If the msgtype and mime type are correct, then it's really a client bug

They unfortunately are'nt:
What the bridge sends (stripped):
```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.file",
    "info": {
      "mimetype": "application/ogg"
    }
  },
}
```

What the same audiofile (with `.ogg` at the end) send via riot-web looks like:
```json
{
  "type": "m.room.message",
  "content": {
    "info": {
      "mimetype": "audio/ogg"
    },
    "msgtype": "m.audio",
  },
}
```

**Comment by tulir** [comment]
Normal voice messages on telegram seem to be bridged correctly for me. Make sure you have the latest bridge version. If the problem is still there, forward something that isn't bridged correctly to me ([t.me/tulir](https://t.me/tulir))

**Comment by tulir** [comment]
Looks like some (old?) versions of magic might return `application/ogg` instead of `audio/ogg` as the mime type, and the bridge depends completely on the prefix of the mime type (`audio/`, `image/`, etc) to determine the msgtype. Probably needs a special case to replace `application/ogg` with `audio/ogg`
