### ISSUE TITLE
Telegram->Matrix deletes don't get bridged

### ISSUE THREAD

**Issue by z3ntu** [tulir/mautrix-telegram#421]
It seems that Telegram to Matrix deletes aren't bridged properly; deleting a message in Matrix deletes it on Telegram as well so that direction works fine.

Seen on the feneas.org instance of the bridge

**Comment by tulir** [comment]
Deletions are bridged, but sometimes Telegram doesn't feel like telling users that a message was deleted. Not much the bridge can do about it.
