### ISSUE TITLE
Direct chats are recreated after restarting the bridge

### ISSUE THREAD

**Issue by KRE02** [tulir/mautrix-telegram#425]
With config option `sync_direct_chats` set to `true`, the bridge creates one room per telegram direct chat on startup, even if there is an existing room for the direct chat (also created by the bridge).

After receiving the first message from a telegram user, a new room is created, rendering the room that was created at bridge-startup useless.

Tested on 0.7.1 and 0.7.2-rc1

**Comment by tulir** [comment]
That commit should fix it, but my dev env is slightly broken currently so I haven't tested it

**Comment by KRE02** [comment]
Thank you, I will test it later.
