### ISSUE TITLE
Gate cannot track actions performed by bots

### ISSUE THREAD

**Issue by xvitaly** [tulir/mautrix-telegram#427]
Telegram gate cannot track actions, performed by other bots with admin access rights in supergroup (eg. antispam bots).

Steps to reproduce:
* add any antispam bot to supergroup with admin rights;
* wait until antispam bot will remove spam messages or force it to delete some messages.

Expected action:
Gate should delete all messages, removed by other Telegram bots.

Current action:
No actions performed and spam persists in bridged Matrix room.

Additional information:
I asked some Telegram staff and they said that one bot cannot track events of another and this is a feature, not a bug.

This gate should switch from Telegram Bot API to mtproto (will require a valid telephone number and Telegram account).

**Comment by tulir** [comment]
The bridge has never used the bot API. You can log in with your account to bridge messages sent by bots in chats your account is in. Deletions sometimes don't work properly though
