### ISSUE TITLE
mark messages as read on matrix side when read on telegram

### ISSUE THREAD

**Issue by Bubu** [tulir/mautrix-telegram#428]
Reading a message on matrix correctly marks the message read on TG's side. When using double puppeting it should also do the same the other way around.

When I read a chat/DM on telegram it should be marked as read for my matrix user.

**Comment by Bubu** [comment]
I assume this was closed by b17454723e167a3efead3d7fb3ef1bae00deadd8?

**Comment by tulir** [comment]
Indeed, I forgot to check if there was an existing issue for that

**Comment by Bubu** [comment]
This seems to  be working for DMs but not for group chats. Is that a known problem?

**Comment by tulir** [comment]
No, works fine for me
