### ISSUE TITLE
LICENSE missing from pypi tarball

### ISSUE THREAD

**Issue by pgajdos** [tulir/mautrix-telegram#454]
Hi,

could you please add it?

**Comment by tulir** [comment]
Why and how? It already has the license as a classifier

**Comment by pgajdos** [comment]
Why:
In opensource each piece of software should have LICENSE* along.
https://www.gnu.org/licenses/gpl-howto.html
How:
I do not know, that probably depends how you generate pypi tarball. Many python projects have MANIFEST.in, which does not seem to be this case.

**Comment by auscompgeek** [comment]
I think setuptools has a `license_file` metadata thingo. I presume if it's missing from the source tarball it's also missing from the wheel.

**Comment by tulir** [comment]
Added in 7e8d4bc9a8af4bfeb1fe74a76551ba356f44c25b
