### ISSUE TITLE
Management bot doesn't reply

### ISSUE THREAD

**Issue by tudurom** [tulir/mautrix-telegram#456]
Hi. Whenever I send a message to the management bot, like `help`, no reply shows up. Looking at the bridge's logs and synapse's logs, requests are actually made for the reply, successful too, yet no message shows up. Bridging works normally, I can send and receive to and from telegram rooms just fine.

**Comment by joshua-schnabel** [comment]
I have the same problem. Have you solved the problem?

**Comment by tudurom** [comment]
I gave up on matrix entirely

**Comment by JuniorJPDJ** [comment]
@joshua-schnabel are you using e2be

**Comment by joshua-schnabel** [comment]
Hi, yes I'm using e2be. I fixed the problem by completely dump my synapse instance and build up again.
