### ISSUE TITLE
Support dart animation style messages

### ISSUE THREAD

**Issue by Mimoja** [tulir/mautrix-telegram#457]
When sending the :dart: emoji telegram (android - PlayStore) converts it into an animation with included minigame for hitting that dart. The bridge does not support this message type.

**Comment by tulir** [comment]
Probably not going to fix before telethon makes a new release with the new API layer (LonamiWebs/Telethon@a353ae3b6511592bdb25dbf47075eaeb75a2acdb)

**Comment by Mimoja** [comment]
Thanks for clarification :)
