### ISSUE TITLE
Contact names may leak from bridged users contact lists

### ISSUE THREAD

**Issue by inknos** [tulir/mautrix-telegram#459]
Seems like contact names are leaking.
I am running synapse through [matrix-docker-ansible-deploy](https://github.com/spantaleev/matrix-docker-ansible-deploy/) on a centos7 istance (also tested on Debian 9 same results)

I have two users on the server, me and a friend. We are connected to the bridge through double puppeting. I tested it both with Shared Secret Auth and access token following [this](https://github.com/spantaleev/matrix-docker-ansible-deploy/blob/master/docs/configuring-playbook-bridge-mautrix-telegram.md).

The contacts are leaking this way:
1. The first user that connects sets the display name for the common contacts. For example: John Doe is a common friend. I saved it as John Doe and log in. The other bridged user has Jon Doe saved as JD. He will see him as John Doe. Vice versa is valid. The first that connects decides.
2. Both of us can look for a contact who we do not have in our contact list and who is not even in a group. For example: I can look for family contacts and find the full names and IDs as if they were saved in my contacts too.

I can queryng the synapse db to confirm the user is not in a public room. I can look for the name of the user that is in `user_1` contact list. In this example `@telegram_83950xxxx:domain.im` is in a private group with `user_1` 
```
homeserver=# SELECT * FROM users_who_share_private_rooms WHERE other_user_id LIKE '@telegram_83950xxxx:domain.im';
         user_id          |          other_user_id          |             room_id             
--------------------------+---------------------------------+---------------------------------
 @telegrambot:domain.im | @telegram_83950xxxx:domain.im | !yCvCWLOkKwCzPmjYWV:domain.im
 @user_1:domain.im     | @telegram_83950xxxx:domain.im | !yCvCWLOkKwCzPmjYWV:domain.im
(2 rows)
```
and he is in no public groups.
```
homeserver=# SELECT * FROM users_in_public_rooms WHERE user_id LIKE '@telegram_83950xxxx:domain.im'; 
user_id | room_id
 ---------+--------- 
(0 rows)
```
Again, this applies also for users who are not in groups. The presence of a user in any contact list seems sufficient for his/her name to leak to the other bridged users.

**Comment by tulir** [comment]
The bridge has nothing to do with user search. If you can find users you shouldn't, it's a synapse bug.

Contact list names being shown to other users isn't optimal, but there also isn't really any way to avoid it if the user is in everyones contact lists. Telegram just doesn't provide a way to get the real name (at least not without removing the contact name)

**Comment by inknos** [comment]
Thanks, tulir. I see that the main problem here is synapse sharing contacts. The renaming of common contacts is annoying but not that of a big deal. Should I move the issue to synapse then?

**Comment by inknos** [comment]
Closing this issue because was moved to synapse.
