### ISSUE TITLE
Bot disable one particular type of format instead of bulky formats 

### ISSUE THREAD

**Issue by TNTBOMBOM** [tulir/mautrix-telegram#462]
Im trying to hide/disable the ability of the bot to create notifications when someone join/left/name change in matrix and send it to telegram as well (because this is annoying on telegram side). 

So i got this this page: 

https://github.com/tulir/mautrix-telegram/wiki/Relay-bot#message-format-configuration

if i use the command in this order: 

`!tg config set state_event_formats join: ''`

then 

`!tg config set state_event_formats leave: ''`

then 

`!tg config set state_event_formats name_change: ''`

Then i check using: 

`!tg config view`

it will only show the last command which is: 

```
Room-specific config:

state_event_formats:
    name_change: ''
```

thought maybe if i use the order in one shot maybe how it will work: 

`!tg config set state_event_formats join: '' leave: '' name_change: ''`

but it gave an error: (didnt work)

`Unhandled error while handling command. Check logs for more details (ref: 1588024805).`

So this is a bug or im missing something?

ThX!

**Comment by tulir** [comment]
this is a single command:

```
!tg config set state_event_formats join: ''
leave: ''
name_change: ''
```

if you want it in one line, `!tg config set state_event_formats {"join": "", "leave": "", "name_change": ""}` should work too

`!tg config set state_event_formats.join ''` to set a single field instead of the whole object (note the dot)

**Comment by TNTBOMBOM** [comment]
Alright thank you, better to add this command as one line into the 
github wiki (better understanding). Or add a note copy/paste this 
command as one chunk or so (because its not clear that it should be done 
into one line command)

Thanks agains :)

Tulir Asokan:
> this is a single command:
> 
> ```
> !tg config set state_event_formats join: ''
> leave: ''
> name_change: ''
> ```
> 
> if you want it in one line, `!tg config set state_event_formats {"join": "", "leave": "", "name_change": ""}` should work too
> 
> `!tg config set state_event_formats.join ''` to set a single field instead of the whole object (note the dot)
>
