### ISSUE TITLE
Don't translate Markdown inside of URLs

### ISSUE THREAD

**Issue by Mimoja** [tulir/mautrix-telegram#463]
When postinga link that accidentally contains markdown it will be translated when posted by the bridge while most normal users can post the link with riot just fine.

Take this example:

`https://www.hr6.tum.de/fileadmin/_processed_/c/1/csm_smart__e8029ba795.jpg`

`_PROCESSED_` will be interpreted as _Markdown_ and will render the link unusable. This happens both directions matrix <-> telegram 

Note: some matrix clients appear to break this as well so even the MATRIX<=>MATRIX way does not always work properly.

**Comment by tulir** [comment]
What do you mean exactly? The bridge does no markdown stuff in either direction

**Comment by Mimoja** [comment]
Good to know. Thanks for the fast response.

Let me clarify (if necessary): When I post a telegram message with the link above, then the matrix side (riot-android) gets a broken link displayed. This does not happen if I post directly into the matrix channel.

**Comment by tulir** [comment]
Are you sure it's riot-android and not riotx-android? Sounds like vector-im/riotX-android#350
