### ISSUE TITLE
sync_direct_chats creates useless rooms

### ISSUE THREAD

**Issue by pztrn** [tulir/mautrix-telegram#465]
When option ``bridge - sync_direct_chats: true`` it is syncing private chats by creating new rooms, but when I start chatting using them - bridge creates another room, which will persist and properly sync.

Documentation in configuration says:

```
# Whether or not to sync and create portals for direct chats at startup.
```

So I assumed that private chats will be created and **used** later. Actual behaviour is different and useless at all. Can this be fixed or option be removed, please?

**Comment by js-dot** [comment]
I can confirm this issue. 

Especially, I think it is a duplicate of #425.
