### ISSUE TITLE
Thumbnails for webm animated stickers

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#467]
Currently the bridge sends the WebM file itself as the thumbnail for animated stickers, which means clients like Riot don't show anything before playing them. Either using the existing video thumbnailer or making an additional lottieconverter call to get a png thumbnail should work.

**Comment by unixandria-xda** [comment]
It seems for animated stickers it just sends a link that leads to an invalid file atm

**Comment by tulir** [comment]
If you don't enable conversion, it sends a link to a perfectly valid gzipped JSON file.

**Comment by sot-tech** [comment]
Hello.

I think, that for webm there is no need to call lottieconverter twice: if I'm not mistaken, ffmpeg constructs webm from png series (`pngs` mode), which located in tmp dir, so before calling ffmpeg any of generated png could be used as thumb.
