### ISSUE TITLE
New E2(B)E rooms "unable to decrypt"

### ISSUE THREAD

**Issue by olmari** [tulir/mautrix-telegram#478]
Having both support and default enabled, suddenly all new E2(B)E rooms are not readable on matrix, bridge puppet says `** Unable to decryot: The sender's device has not sent us the keys for this message. **`. This happends on all new E2E initiations. So far existing E2E rooms seems to keep working. Bridge log shows `[DEBUG@mau.e2ee] Got GroupEncryptionError, sharing group session and trying again`.

![TG-bridge E2BE bug](https://user-images.githubusercontent.com/5422161/83871489-cdbdda00-a738-11ea-887b-fc10debbbc27.png)

**Comment by nrj5k** [comment]
I upgraded from the last release (0.7.whatever) to 0.8 and setup encryption and am getting this as well.

**Comment by Mebus** [comment]
I've got the same problem in #490.

Mebus

**Comment by tulir** [comment]
This should work better now that it doesn't use matrix-nio in a hacky way anymore
