### ISSUE TITLE
Photos from album are bridged in bad (random?) order

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#484]
It's important, people often sends ordered photos/screenshots to each other.
Examples are: photos of notes for colleage/school, conversation screenshots

Telegram:
![image](https://user-images.githubusercontent.com/7334549/84579765-217f9180-add1-11ea-922a-31698aa5e037.png)
![image](https://user-images.githubusercontent.com/7334549/84579767-23495500-add1-11ea-93a6-0a85af04dae3.png)

RiotX (Matrix):
![image](https://user-images.githubusercontent.com/7334549/84579769-2c3a2680-add1-11ea-9e99-800be2649549.png)
![image](https://user-images.githubusercontent.com/7334549/84579770-2e9c8080-add1-11ea-9b33-7f2835ff43b2.png)
![image](https://user-images.githubusercontent.com/7334549/84579771-30664400-add1-11ea-8c09-afff4a68c563.png)
![image](https://user-images.githubusercontent.com/7334549/84579775-32c89e00-add1-11ea-88b9-42de8b622fa4.png)

**Comment by tulir** [comment]
Moved to #505
