### ISSUE TITLE
When multiple messages are forwarded on telegram, they come to matrix on random order

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#486]
It is veery annoying issue, people are often forwarding messages to each other on telegram.

Example:
Telegram:
![image](https://user-images.githubusercontent.com/7334549/85056801-23b26900-b1a0-11ea-9c19-dc00c16e68fb.png)
RiotX:
![image](https://user-images.githubusercontent.com/7334549/85056817-290fb380-b1a0-11ea-8013-dc6696a36e1d.png)

**Comment by ludwigbald** [comment]
Does Telegram guarantee message order?
Do messages sometimes get jumbled in Telegram -> Telegram conversations?

If so, it's not the bridge's fault.

**Comment by tulir** [comment]
It is the bridge's fault, but the bridge needs matrix-org/matrix-doc#2246 to handle all messages in order.

**Comment by JuniorJPDJ** [comment]
This is problem even without media in message :/
And yes - telegram guarants order, but it seems that you already know that.

**Comment by tulir** [comment]
Moved to #505
