### ISSUE TITLE
unable to decrypt error in manualy created direct chat

### ISSUE THREAD

**Issue by L0ric0** [tulir/mautrix-telegram#497]
with e2be enabled when starting a direct chat with a user returned by the `search` command results in ab unable to decrypt error. direct chats created by the bridge (for example with the `pm` command) are fine and work as intended.

(e2ee is enabled by default from the synapse side)

**Comment by tulir** [comment]
> (e2ee is enabled by default from the synapse side)

you either need to enable it in the bridge config or manually invite the bridge bot
