### ISSUE TITLE
Automatic new group in matrix (and reverse if possible)

### ISSUE THREAD

**Issue by HKalbasi** [tulir/mautrix-telegram#502]
I use this wonderful bridge to leave Telegram. I usually find myself in making a group in matrix, adding bot into groups, get id from telegram and sending it to matrix and ... I have many groups and this is a tedious process.

Automating this process would be great. A "new" button can be added in addition to "id" button, that automatically creates a matrix group, bridge it to the telegram group and sends the link of matrix room in telegram.

**Comment by tulir** [comment]
`/portal` does that (https://github.com/tulir/mautrix-telegram/wiki/Relay-bot#commands)

You can also just log into the bridge to get all your chats bridged automatically.

**Comment by HKalbasi** [comment]
Thank you. That's it! But why only the "/id" command is suggested by telegram?
