### ISSUE TITLE
When image with caption is deleted on telegram side only caption is deleted on matrix side

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#509]
Image is still here
![Screenshot_20200808_150431](https://user-images.githubusercontent.com/7334549/89711113-7c280a80-d988-11ea-9de8-54729643e116.png)
![Screenshot_20200808_150504](https://user-images.githubusercontent.com/7334549/89711120-8cd88080-d988-11ea-97f4-cdab29619a27.png)

**Comment by tulir** [comment]
Moved to #511
