### ISSUE TITLE
Reply to image with caption splitted to 2 messages on matrix side works only on caption

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#510]
# Image without caption (working as expected):
## Telegram:
![Screenshot_20200808_150548](https://user-images.githubusercontent.com/7334549/89711151-c0b3a600-d988-11ea-8cab-7773da4ce6f6.png)

## Element:
![Screenshot_20200808_150644](https://user-images.githubusercontent.com/7334549/89711156-c8734a80-d988-11ea-8c44-5ae004f3beb4.png)

# Image with caption (bugged - reply on image not bridged to telegram):
## Telegram:
![Screenshot_20200808_150724](https://user-images.githubusercontent.com/7334549/89711174-e5a81900-d988-11ea-80d4-e2ba8f1c8a1f.png)
![Screenshot_20200808_150804](https://user-images.githubusercontent.com/7334549/89711186-f789bc00-d988-11ea-9d85-b183f0c1c4ca.png)

## Element:
![Screenshot_20200808_150833](https://user-images.githubusercontent.com/7334549/89711200-08d2c880-d989-11ea-8248-967c54044c1b.png)
![Screenshot_20200808_150849](https://user-images.githubusercontent.com/7334549/89711207-125c3080-d989-11ea-90df-d32234f1c26c.png)

**Comment by tulir** [comment]
Moved to #511
