### ISSUE TITLE
Add connection pool options

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#519]
To avoid errors like:
```
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30
```

**Comment by tulir** [comment]
wait, how is it possible for it to evem use more than one connection at a time?

**Comment by turt2live** [comment]
sqlalchemy just does, particularly in async/await code when it's trying to do many things.

**Comment by tulir** [comment]
I mean sqlalchemy is synchronous and the bridge is asyncio. How can it run more than one query at a time?

**Comment by turt2live** [comment]
multiple connections in a pool isn't unheard of, even if they are all idle. The bridge does have active transactions though

**Comment by tulir** [comment]
All SQLAlchemy options can now be set with the [`database_opts`](https://github.com/tulir/mautrix-telegram/blob/v0.9.0-rc1/mautrix_telegram/example-config.yaml#L34-L35) config option
