### ISSUE TITLE
After logout + login bot fails to bridge DMs

### ISSUE THREAD

**Issue by JuniorJPDJ** [tulir/mautrix-telegram#522]
At some point I invalidated session on telegram side,
I had to logout, bridge kicked me off from all chats and after relogin...
It fails to join DMs back.
Group chats work good.

**Comment by JuniorJPDJ** [comment]
It still creates new DMs when I start writing with new person.
It fails to create/invite me to DMs which were created before logout.

**Comment by tulir** [comment]
Probably duplicate of #397
