### ISSUE TITLE
issue while fetching docker image

### ISSUE THREAD

**Issue by Mimoja** [tulir/mautrix-telegram#525]
```
ERROR: for mautrix-telegram  Get https://dock.mau.dev/v2/: remote error: tls: internal error
ERROR: Get https://dock.mau.dev/v2/: remote error: tls: internal error
```

**Comment by tulir** [comment]
Everything seems to be working fine, are your system TLS libraries and trust stores up to date?

**Comment by Mimoja** [comment]
Tried it on several devices on ubuntu 18.04, 20.04 , 20.10 and debian buster. Worked just now. Maybe just a hiccup or a networking issue. Sorry for the useless ticket. Next time it is again a smart one. Promised
