### ISSUE TITLE
Displaynames of ghosts alternate between set and custom names.

### ISSUE THREAD

**Issue by Half-Shot** [tulir/mautrix-telegram#533]
![image](https://user-images.githubusercontent.com/2072976/97781135-58d4bc00-1b81-11eb-808c-73a448517ed7.png)

This seems to happen roughly when Borealis talks. "Boris Egg" is my custom name for him in Telegram.

**Comment by olmari** [comment]
I can confirm such behaviour happening on at least one person that is using native telegram bridged to some hacklab.fi channels. Occasionally this has been talked about in chat, but I think actual bug finding has not been occurred yet despite some looking around.

**Comment by Half-Shot** [comment]
context: https://matrix.to/#/!FDTDciUzgMWGJcYnwn:maunium.net/$CQbsjFdy3PAMX-9FgUhjjXhBQ2yDnc2w4GjQfsNswHc?via=maunium.net&via=matrix.org&via=tchncs.de

**Comment by JuniorJPDJ** [comment]
Yes, sometimes name of person is being set to name of him from bridge user's contacts.
If I have 2 users of a bridge, both set someone's name in personal contact, bridge will change this name to one of set names, names will change occasionally to the second one >__<
Is there a way to just set person's public name? Not from personal contacts?
