### ISSUE TITLE
0.9.0-rc1 doesn't install a program in bin anymore

### ISSUE THREAD

**Issue by BrainDamage** [tulir/mautrix-telegram#535]
running python setup.py install in 0.9.0-rc1 doesn't install anymore a launching script under $prefix/bin anymore, making the program extremely hard to use for the non-pythhon savy

**Comment by tulir** [comment]
Why are you running `python setup.py install`? The [setup instructions](https://github.com/tulir/mautrix-telegram/wiki/Bridge-setup) explain how to install and run the bridge.

**Comment by BrainDamage** [comment]
because I am making a distro package

**Comment by tulir** [comment]
You should probably just include your own entrypoint script in the package
