### ISSUE TITLE
pm chats are created as rooms sometimes

### ISSUE THREAD

**Issue by karlprieb** [tulir/mautrix-telegram#539]
Why pm chats are created as rooms sometimes?
If I run the command `pm @telegramHandler` the bot answer with: `Created private chat room with Name`. But in fact the bot create a room.
If I leave the room and run the same command again the bot create the private chat room as expected.
Is there some configuration that I should look?

**Comment by karlprieb** [comment]
But sometime the bot create the right type of room on the first time.
The same applies to when I receive some message from a pm on telegram that I still don't have on Matrix, sometime the bot automatically create a group room instead of a private chat room.

**Comment by tulir** [comment]
There isn't any actual difference between rooms and private chats and the bridge can't reliably set which one a room is. You can use [`sync_direct_chat_list`](https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/example-config.yaml#L177-L180) to make the bridge set it in your account (requires double puppeting/`login-matrix`)
