### ISSUE TITLE
Backfill specific chat (post re-install)

### ISSUE THREAD

**Issue by IngwiePhoenix** [tulir/mautrix-telegram#545]
I accidentially completely broke my Synapse DB and had to start _everything_ over - including the Telegram integration.

One thing I noticed after doing a `sync` is that while my groups are automatically bridged again, but my private chats are not - let alone being backfilled. Is there a way to backfill a specific private chat?

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-telegram/wiki/Creating-and-managing-chats#private-messages
