### ISSUE TITLE
Messages ending with a space show up twice in matrix group chats

### ISSUE THREAD

**Issue by f4814** [tulir/mautrix-telegram#553]
The bridge will duplicate any message sent to a group chat, if the message ends in a space. The duplicate only shows up in matrix.
For some reason there is no message duplication in private chats.

The bridge logs show nothing interesting.

**Comment by chagai95** [comment]
tested, happening to me as well, thanks for reporting! Also happens for other events, not sure exactly when

**Comment by tulir** [comment]
This only applies to non-supergroups, which are bad and should be upgraded (#146)

**Comment by chagai95** [comment]
solved it, thanks!
