### ISSUE TITLE
E2BE not working "the bridge hasn't received the decryption keys"

### ISSUE THREAD

**Issue by theCalcaholic** [tulir/mautrix-telegram#562]
I think, #478 might be back.

Whenever I enable E2E-Encryption, I will continue to receive messages from Telegram, but not vice versa.
Additionally, the following message is shown by the bridge bot:

```
Your message was not bridged: the bridge hasn't received the decryption keys. If this error keeps happening, try restarting your client.
```

Whenever I write something in an encrypted room with the bridge, I see something like this in the logs:
```
Dez 21 21:20:19 Debian-105-buster-64-minimal matrix-mautrix-telegram[18621]: [2020-12-21 20:20:19,366] [DEBUG@mau.bridge.e2ee] Didn't find session <REDACTED> waiting 5 seconds for session to arrive
Dez 21 21:20:19 Debian-105-buster-64-minimal matrix-mautrix-telegram[18621]: [2020-12-21 20:20:19,367] [INFO@aiohttp.access] 172.23.0.5 [21/Dec/2020:20:20:19 +0000] "PUT /transactions/1152?access_token=<REDACTED> HTTP/1.1" 200 158 "-" "Synapse/1.24.0"
Dez 21 21:20:24 Debian-105-buster-64-minimal matrix-mautrix-telegram[18621]: [2020-12-21 20:20:24,368] [WARNING@mau.mx] Didn't find session <REDACTED>, waiting even longer
```

I have already attempted clean reinstalls (including all other server components), without any result.

**Comment by tulir** [comment]
Looks like your synapse is broken, probably not related to the bridge

**Comment by theCalcaholic** [comment]
Thanks for your response. Do you have any idea how to debug this? If not, the issue can be closed, as I'm unsure how to continue from here (I could maybe take it upstream, though).

**Comment by theCalcaholic** [comment]
@tulir So, I did some digging and I found the following in Synapse's logs:

1.
```
Dez 22 00:12:44 Debian-105-buster-64-minimal matrix-synapse[15973]: 2020-12-21 23:12:44,522 - synapse.http.matrixfederationclient - 577 - WARNING - POST-2294 - {POST-O-68} [matrix.org] 
Dez 22 00:12:56 Debian-105-buster-64-minimal matrix-synapse[15973]: 2020-12-21 23:12:56,311 - synapse.crypto.keyring - 594 - WARNING - POST-2297 - Key lookup failed from 'matrix.org': N
```
This looks like it might be related. If mautrix-telegram were to request a key from matrix.org, that would most likely be wrong?

2.
```
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]: 2020-12-21 23:14:10,181 - synapse.http.server - 79 - ERROR - GET-2466 - Failed handle request via 'SyncRestServlet': 
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]: Traceback (most recent call last):
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 224, in _async_render_wrapper
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     callback_return = await self._async_render(request)
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/http/server.py", line 400, in _async_render
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     callback_return = await raw_callback_return
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/rest/client/v2_alpha/sync.py", line 173, in on_GET
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     sync_result = await self.sync_handler.wait_for_sync_for_user(
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 280, in wait_for_sync_for_user
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     res = await self.response_cache.wrap(
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/twisted/internet/defer.py", line 1418, in _inlineCallbacks
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     result = g.send(result)
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 312, in _wait_for_sync_for_user
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     result = await self.current_sync_for_user(
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 344, in current_sync_for_user
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     return await self.generate_sync_result(sync_config, since_token, full_state)
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:   File "/usr/local/lib/python3.8/site-packages/synapse/handlers/sync.py", line 978, in generate_sync_result
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]:     raise NotImplementedError()
Dez 22 00:14:10 Debian-105-buster-64-minimal matrix-synapse[15973]: NotImplementedError
```
This is quite interesting as well - It seems to be caused by a deprecated function for App Services, when they are [calling /sync or /events](https://github.com/matrix-org/matrix-doc/issues/1144)

Here's the line where the Error is raised: https://github.com/matrix-org/synapse/blob/develop/synapse/handlers/sync.py#L978

I'm still not 100% sure which of these error messages __could__ be related to e2e encryption in mautrix-telegram (if any).
But I figured, I'd share these findings anyway.

**Comment by tulir** [comment]
That internal server error is most likely the reason it's not working. The error is essentially a bug in synapse, the devs still haven't accepted the simple PR to fix it.

There's a workaround in the bridge, but old installations must apply it manually (or regenerate the registration file), see the wiki for instructions: https://github.com/tulir/mautrix-telegram/wiki/End‐to‐bridge-encryption#registration-file-workaround

**Comment by theCalcaholic** [comment]
Thanks, I'll try that. But what is that as_token and how do I retrieve it?

Sorry for my noob questions :)

**Comment by theCalcaholic** [comment]
So, I attempted to apply the workaround, but it didn't resolve my issue.
If I read the instructions correctly, I shouldn't even need it, since I have synapse v1.24.0 and mautrix-telegram v0.9.0 (both freshly installed).
But I think I need to get my head of the topic for a bit. I'll have another look at it tomorrow and see if I can pinpoint the issue. :)

Thanks again for the support!

**Comment by pimeys** [comment]
I'm having the same error in a fresh install of Synapse, with both the Telegram and Signal bridges.

**Comment by tchapi** [comment]
Same discussion in Signal, for reference: https://github.com/tulir/mautrix-signal/issues/43

**Comment by tulir** [comment]
Indeed, this looks like the same problem in the playbook

**Comment by gabrix73** [comment]
Same here for mautrix-whatsapp .

**Comment by N3oTraX** [comment]
Hi, same here for mautrix-whatsapp here too.
