### ISSUE TITLE
How to get the displayname for all contacts?

### ISSUE THREAD

**Issue by matzebond** [tulir/mautrix-telegram#570]
Most of my contacts show up as `telegram_XXXXXX` (username) instead of `NAME (Telegram)` (displayname).
Actually only groups and private chats with telegram bots have the same name as in Telegram (displayname) but all of my other private chats don't have a displayname and only the username is shown.

I did not change the relevant parts of the config
```
username_template: telegram_{userid}
alias_template: telegram_{groupname}
displayname_template: '{displayname} (Telegram)'
displayname_preference:
- full name
- first name
- username
- phone number
```

What am I doing wrong or is this a general limitation?

**Comment by glenroy37** [comment]
I have a similar problem, but some contacts (only about 5%) show up correctly. It also seems quite random which contacts have the display name and which have telegram_XXXXX

**Comment by elderec** [comment]
I'm also experiencing the problem described above. Only a handful of contacts show up as display name, rest are telegram_XXX. Groups are fine.

**Comment by breuerfelix** [comment]
i experienced the same issue and then i found out that these people do not have a displayname nor username set in their telegram profile. the smartphone is then syncing the number with the name you set in your phone contacts and displays this one.  
that would lead me to the questions: are you able to set a custom name to a telegram puppet ?

**Comment by matzebond** [comment]
I recently joined a Group and all contacts I don't have in my address book (for which Telegram shows "Add to Contacts") have the correct name. For those that are in my (Telegram?) address book it does not matter whether they have a Telegram username or not they show up as telegram_XXX.

I am able to set a custom displayname via `!tg set-displayname NEWNAME` but this it tedious and I don't know how to put whitespace in the name because `mxid is required`. What is mxid supposed to be? I tried the XXX userid (aka `!tg id`) number and the full matrix id, what am I doing wrong?

**Comment by breuerfelix** [comment]
i can confirm that i am also not able to set whitespace since i haven't figured out what the mxid is ... :S

**Comment by matzebond** [comment]
One further report:
Mentions on Telegram like `@telegramusername` are recognized and replaced to `telegram_XXX` on the matrix side.

**Comment by WhiteTomX** [comment]
> 
> 
> i can confirm that i am also not able to set whitespace since i haven't figured out what the mxid is ... :S

The mixid is the complete id of the user so for example `set-displayname New Name @telegram_123456:server.de` should work.

**Comment by matzebond** [comment]
@tulir thank you very much for the fix.

@WhiteTomX thanks this works. I thought I tried that but apparently I did not...
