### ISSUE TITLE
Another bot user kicked out automatically after invite from admin

### ISSUE THREAD

**Issue by rakshazi** [tulir/mautrix-telegram#576]
Hello!
I configured telegram bridge as telegram client, logged in and joined the chat group (chat group created on telegram side and was synced to matrix as portal room), it works perfectly.

But when I tried to invite webhook bot to the room on matrix side, it was kicked by telegram bot automatically, here is log:
```
admin invited _webhook.
_webhook joined the room.
Telegram bridge bot kicked _webhook. Reason: This chat does not have a bot relaying messages for unauthenticated users.
```

Could you explain me how to keep invited by admin users (even bots) in that room, please?

**Comment by tulir** [comment]
Is the error message not accurate?

**Comment by rakshazi** [comment]
Oh, thank you, i'll try this (just never configured such integrations before)
