### ISSUE TITLE
rtl languages with ltr sender username

### ISSUE THREAD

**Issue by HKalbasi** [tulir/mautrix-telegram#592]
Unicode bidi algorithm look for first character of a paragraph and determine direction based on it. So when user handle is in ltr language, All of message in telegram will be ltr, but maybe it should be in rtl:
<pre>
Correct:
sender: &#x2068;این x است.
Wrong (current state):
sender: این x است.
</pre>
This can easily solved by insert an isolation character u+2068 before message text (after space). [More info](https://www.unicode.org/reports/tr9/#Explicit_Directional_Isolates)

**Comment by arhayati** [comment]
+1 for this. Very needed.

**Comment by DearRude** [comment]
Any updates on this?

**Comment by HKalbasi** [comment]
I talked to maintainer, he said the bot is configurable so there is no interest in fix this in source code. So I will close this issue after this comment.

Room admins and bot owners can configure bot to handle this. The message sent by bot is styled with `messageformats.m.text` which is equal to `<b>$sender_displayname</b>: $message` by default. You can add isolation character, but my suggestion is adding a break line that not only fix this problems, but also make a more readable and better experience. Room admin can do this by sending this message to the room:
```
!tg config set message_formats m.text: <b>$sender_displayname</b>:<br>$message
```
