### ISSUE TITLE
Cannot generate registration.yaml

### ISSUE THREAD

**Issue by itsscb** [tulir/mautrix-telegram#595]
OS: Debian Buster

I had the bridge up and running with sqlite for testing. After installing the bridges mautrix-whatsapp (sqlite) and mautrix-signal (postgres) for initial testing I decided to migrate the two sqlite to postgres. So I removed the venvs and directories of mautrix-whatsapp and mautrix-telegram and installed both from scratch. 
The mautrix-whatsapp & mautrix-signal bridges are both running fine with postgres.
But the mautrix-telegram bridge can't generate the registration.yaml.

The following error occurs while running `python -m mautrix_telegram -g`:

> 'Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix_telegram/__main__.py", line 22, in <module>
    from mautrix.util.db import Base
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/__init__.py", line 1, in <module>
    from .base import Base, BaseClass
  File "/opt/mautrix-telegram/lib/python3.7/site-packages/mautrix/util/db/base.py", line 11, in <module>
    from sqlalchemy.engine.result import RowProxy, ResultProxy
ImportError: cannot import name 'RowProxy' from 'sqlalchemy.engine.result' (/opt/mautrix-telegram/lib/python3.7/site-packages/sqlalchemy/engine/result.py)

Unfortunately I am stuck. Could you push me into the right direction?

I followed the instructions from the documentation (mautrix-telegram[all]) [https://docs.mau.fi/bridges/python/setup/index.html?bridge=telegram](https://docs.mau.fi/bridges/python/setup/index.html?bridge=telegram)

Here my config.yaml
[config.yaml](https://github.com/tulir/mautrix-telegram/files/6144260/config.txt)

Edit: Forgot to mention that it doesn't even run with sqlite now.

**Comment by MFAshby** [comment]
For anyone else that finds this: installing the current `master` version instead of the latest release works.

See [installation](https://docs.mau.fi/bridges/python/setup/index.html?bridge=telegram#production-setup), under 'if you want the master branch'
