### ISSUE TITLE
Audio message not supported in element android

### ISSUE THREAD

**Issue by zaibon** [tulir/mautrix-telegram#598]
I'm not sure this is a bridge bug or a element client bug, but when I receive an audio message from telegram I'm not able to listen to it.
Here how it looks like from my client :
 ![Screenshot_20210318-124709.jpg](https://user-images.githubusercontent.com/303164/111621291-1afeca00-87e8-11eb-950a-18dcf58e2231.jpg)

**Comment by frederictobiasc** [comment]
Voice-Messages from the bridges in pills are already supported in element-desktop:
![audio-pill](https://user-images.githubusercontent.com/26125115/120788682-e837b880-c530-11eb-90f2-50e51da2f24b.png)
For android currently: As the error message states: If you install an application that can handle the audio format, you can play it. On my phone, VLC plays the message.
So you're safe to close here and check out: https://github.com/vector-im/element-android/issues/29

**Comment by Zebra72** [comment]
I have VLC installed too but, when I click on the link, I'm redirected to the app choose window, I select VLC but it never plays the audio file

**Comment by frederictobiasc** [comment]
Could you try google files? I just tested it and it works also:
![img1](https://user-images.githubusercontent.com/26125115/120792848-6a76ab80-c536-11eb-8d0c-810e25779ebf.png)

![img2](https://user-images.githubusercontent.com/26125115/120793092-bfb2bd00-c536-11eb-8322-e1bb88c37f6b.png)

**Comment by Zebra72** [comment]
I don't have Google files but tried with YouTube music and it works. Thank you! Still don't working with vlc on witch permissions are OK.

**Comment by zaibon** [comment]
It works for me too with YouTube music.
Closing this 😉
