### ISSUE TITLE
as User I want the messages that are received and read in Matrix to be marked as read on Telegram

### ISSUE THREAD

**Issue by ykktrcb7** [tulir/mautrix-telegram#607]
## Description
1. user receives message inTelegram
2. message is bridged to Matrix
3. user reads/views message
4. bridge marks the same message as read on Telegram

**Comment by tulir** [comment]
This is how the bridge works already, although ephemeral event bridging requires [double puppeting](https://docs.mau.fi/bridges/general/double-puppeting.html) or enabling `ephemeral_events` in the config and registration file.

**Comment by ykktrcb7** [comment]
- changed in the config file:
`ephemeral_events: true`
`sync_with_custom_puppets: false`

- added to registration:
```
appservice:
    ephemeral_events: true
```

.. and restarted the containers.

Is there anything im missing? Telegram still shows all messages unread instead of read.

**Comment by ykktrcb7** [comment]
generated registration file again instead of manually updating it, restarted containers. everything working. thank you
