### ISSUE TITLE
Error: cannot import name 'UpdatePinnedMessages' from 'telethon.tl.types'

### ISSUE THREAD

**Issue by nicfab** [tulir/mautrix-telegram#610]
Hi!
After running command `python -m mautrix_telegram -g` I receive the following error:
**ImportError: cannot import name 'UpdatePinnedMessages' from 'telethon.tl.types' (/opt/matrix-bridges/mautrix-telegram/lib/python3.8/site-packages/telethon/tl/types/__init__.py)**
How can I go ahead?

**Comment by tulir** [comment]
Sounds like you installed an outdated version of Telethon

**Comment by nicfab** [comment]
I run the command `pip install --upgrade mautrix-telegram[all]` and so it is installed Telethon 1.17.
I try to uninstall Telethon and reinstall the latest version but it doesn't work

**Comment by schorschfunke** [comment]
I have the same issue. Telethon version is 1.21.1

**Comment by schorschfunke** [comment]
I've updated to  10rc1, and now it works

**Comment by nicfab** [comment]
I solved running the following command:

`pip install --upgrade telethon`

In this way, it will install the latest version of telethon.
