### ISSUE TITLE
Markdown mask Asterisk

### ISSUE THREAD

**Issue by eest9** [tulir/mautrix-telegram#618]
Hi,

in German \* is commonly used to include all gender identities. Matrix uses backslashes in their markdown language to mask Asterisk so that text don't become italic. It appears that this doesn't work with this telegram bridge.

Is there a way to mask Asterisk in your telegram bridge in order to avoid italic texts? Or is this a bug which should get fixed?

**Comment by tulir** [comment]
The bridge doesn't use markdown anywhere

**Comment by eest9** [comment]
Then why do text become italic?

**Comment by tulir** [comment]
It doesn't become italic. You didn't provide enough info to determine what's actually happening

**Comment by eest9** [comment]
I've reproduced my bugreport now at the portal with my saved massages chat in telegram (but it works in every portal)
Input 1:
![Bildschirmfoto von 2021-05-02 15-05-43](https://user-images.githubusercontent.com/11019106/116814217-fa03f580-ab57-11eb-80a4-87e39416bbb0.png)
Output 1:
![Bildschirmfoto von 2021-05-02 15-05-54](https://user-images.githubusercontent.com/11019106/116814220-fd977c80-ab57-11eb-9511-e69dc5a81d4b.png)
Input 2:
![Bildschirmfoto von 2021-05-02 15-06-09](https://user-images.githubusercontent.com/11019106/116814222-00926d00-ab58-11eb-8227-9237797c2835.png)
Output 2:
![Bildschirmfoto von 2021-05-02 15-06-14](https://user-images.githubusercontent.com/11019106/116814223-025c3080-ab58-11eb-87c2-22d74a9de973.png)

**Comment by tulir** [comment]
Which side are those from? What do the events on Matrix contain (context menu -> view source)?

**Comment by eest9** [comment]
this are sent from the matrix account.
source 1:
```
{
  "type": "m.room.message",
  "sender": "@eest9:cyber-missile.io",
  "content": {
    "msgtype": "m.text",
    "body": "schüler*innen und lehrer*innen",
    "format": "org.matrix.custom.html",
    "formatted_body": "schüler<em>innen und lehrer</em>innen"
  },
  "origin_server_ts": 1619960752052,
  "unsigned": {
    "age": 94,
    "transaction_id": "m1619960751962.240"
  },
  "event_id": "$WwwOFbWmQBOrY7JgPQ-vJ8BKqH6KdRs3LMUpyhXy74U",
  "room_id": "!myZtRXukDtSwaTPSYP:cyber-missile.io"
}
```

source 2:
```
{
  "type": "m.room.message",
  "sender": "@eest9:cyber-missile.io",
  "content": {
    "msgtype": "m.text",
    "body": "schüler\\*innen und lerer\\*innen"
  },
  "origin_server_ts": 1619960773546,
  "unsigned": {
    "age": 244,
    "transaction_id": "m1619960773466.241"
  },
  "event_id": "$A5QroCqwZ5hrss7NjGDEczonenVUAXamiIgzSLxyHXE",
  "room_id": "!myZtRXukDtSwaTPSYP:cyber-missile.io"
}
```

**Comment by tulir** [comment]
The first message is italic on Matrix too (`<em>` tags), the second message has the backslashes in the body. Markdown parsing happens in your client, the bridge is handling both of those correctly.

**Comment by Kunsi** [comment]
@eest9 In Element (atleast Web and Desktop) you can use /plain to disable markdown processing. I suppose other clients offer such a functionality, too.

**Comment by eest9** [comment]
@tulir The problem is that this problem occurs exclusively in portal rooms. Other rooms handle the text just fine.

@Kunsi thanks I'll try this.

**Comment by tulir** [comment]
Being a portal room doesn't affect markdown parsing in Matrix clients at all.

**Comment by eest9** [comment]
@tulir I thought so too, but apparently it does and I don't get why. That's why I'm reporting this.

**Comment by tulir** [comment]
I'm pretty sure it doesn't, but even if it does, it's not a bridge problem.
