### ISSUE TITLE
Building wheel for python-olm error

### ISSUE THREAD

**Issue by cbrhaze** [tulir/mautrix-telegram#619]
Hi there.
I've googled around this issue outside of the bridge itself, installed python-olm and olm-devel via apt, but still experiencing this issue on Debian 10.
I have a working Synapse/Riot instance and trying to get the bridge working:

According [to the setup guide](https://docs.mau.fi/bridges/python/setup/index.html?bridge=telegram) when executing **pip install --upgrade mautrix-telegram[all]** getting this error below. Could you please help me with any ideas to try more?)

Requirement already satisfied: pyasn1>=0.1.3 in ./lib/python3.7/site-packages (from rsa->telethon<1.18,>=1.17->mautrix-telegram[all]) (0.4.8)
Building wheels for collected packages: python-olm
  Building wheel for python-olm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /root/bin/python3 -u -c import io, os, sys, setuptools, tokenize; sys.argv[0] = /tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/setup.py __file__=/tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/setup.py;f = getattr(tokenize, open, open)(__file__) if os.path.exists(__file__) else io.StringIOfrom setuptools import setup; setup());code = f.read().replace(\r\n,\n);f.close();exec(compile(code, __file__, exec) bdist_wheel -d /tmp/pip-wheel-qjxkte6z
       cwd: /tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/
  Complete output (29 lines):
  make: *** No rule to make target../include/olm/olm.h, needed by include/olm/olm.h.  Stop.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/olm
  copying olm/__version__.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/pk.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/__init__.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/utility.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/sas.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/_finalize.----------------------------------------
  ERROR: Failed building wheel for python-olm
  Running setup.py clean for python-olm
Failed to build python-olm
Installing collected packages: python-olm, pycryptodome, psycopg2-binary, prometheus-client, moviepy, mautrix-telegram, cryptg, cchardet, brotli, asyncpg, aiodns
    Running setup.py install for python-olm ... error
    ERROR: Command errored out with exit status 1:
     Stop.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/olm
    copying olm/__version__.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/pk.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/__init__.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/utility.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/sas.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/_finalize.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/session.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/group_session.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/_compat.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/account.py -> build/lib.linux-x86_64-3.7/olm
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.7/_libolm.c'
    creating build/temp.linux-x86_64-3.7----------------------------------------
  ERROR: Failed building wheel for python-olm
  Running setup.py clean for python-olm
Failed to build python-olm
Installing collected packages: python-olm, pycryptodome, psycopg2-binary, prometheus-client, moviepy, mautrix-telegram, cryptg, cchardet, brotli, asyncpg, aiodns
    Running setup.py install for python-olm ... error
    ERROR: Command errored out with exit status 1:
     Stop.
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/olm
    copying olm/__version__.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/pk.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/__init__.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/utility.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/sas.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/_finalize.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/session.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/group_session.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/_compat.py -> build/lib.linux-x86_64-3.7/olm
    copying olm/account.py -> build/lib.linux-x86_64-3.7/olm
    running build_ext
    generating cffi module 'build/temp.linux-x86_64-3.7/_libolm.c'
    creating build/temp.linux-x86_64-3.7
    building '_libolm' extension
    creating build/temp.linux-x86_64-3.7/build
    creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/root/include/python3.7m -c build/temp.linux-x86_64-3.7/_libolm.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_libolm.o -I../include
    build/temp.linux-x86_64-3.7/_libolm.c:50:14: fatal error: pyconfig.h: No such file or directory
     #    include <pyconfig.h>
                  ^~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ueoyy0q9/install-record.txt --single-version-externally-managed --compile --install-headers /root/include/site/python3.7/python-olm Check the logs for full command output.

    building '_libolm' extension
    creating build/temp.linux-x86_64-3.7/build
    creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/root/include/python3.7m -c build/temp.linux-x86_64-3.7/_libolm.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_libolm.o -I../include
    build/temp.linux-x86_64-3.7/_libolm.c:50:14: fatal error: pyconfig.h: No such file or directory
     #    include <pyconfig.h>
                  ^~~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /root/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-7qhdm5hu/python-olm_b54aecf802dd4fcf8586348c92b75a7e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ueoyy0q9/install-record.txt --single-version-externally-managed --compile --install-headers /root/include/site/python3.7/python-olm Check the logs for full command output.
py -> build/lib.linux-x86_64-3.7/olm
  copying olm/session.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/group_session.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/_compat.py -> build/lib.linux-x86_64-3.7/olm
  copying olm/account.py -> build/lib.linux-x86_64-3.7/olm
  running build_ext
  generating cffi module 'build/temp.linux-x86_64-3.7/_libolm.c'
  creating build/temp.linux-x86_64-3.7
  building '_libolm' extension
  creating build/temp.linux-x86_64-3.7/build
  creating build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.7m -I/root/include/python3.7m -c build/temp.linux-x86_64-3.7/_libolm.c -o build/temp.linux-x86_64-3.7/build/temp.linux-x86_64-3.7/_libolm.o -I../include
  build/temp.linux-x86_64-3.7/_libolm.c:50:14: fatal error: pyconfig.h: No such file or directory
   #    include <pyconfig.h>
                ^~~~~~~~~~~~
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by tulir** [comment]
https://docs.mau.fi/bridges/python/optional-dependencies.html

![image](https://user-images.githubusercontent.com/4224639/116978015-d2359e80-accb-11eb-922c-d4179fb803e4.png)

**Comment by cbrhaze** [comment]
@tulir thanks for your response. I installed both these 3 packages from the default apt repo. I'm running Debian 10, so there where no issues to locate them. However, after restarting, I still get the same. I would appreciate your help as nothing seems to be missing here.

compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for python-olm
  Running setup.py clean for python-olm
Failed to build python-olm
Installing collected packages: python-olm, pycryptodome, psycopg2-binary, prometheus-client, moviepy, mautrix-telegram, cryptg, cchardet, brotli, asyncpg, aiodns
    Running setup.py install for python-olm ... error
    ERROR: Command errored out with exit status 1:
     command: /root/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-69i0rh3c/python-olm_8bff554d6a4641cb8446f4274bbc2fbf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-69i0rh3c/python-olm_8bff554d6a4641cb8446f4274bbc2fbf/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-09r6583l/install-record.txt --single-version-externally-managed --compile --install-headers /root/include/site/python3.7/python-olm
         cwd: /tmp/pip-install-69i0rh3c/python-olm_8bff554d6a4641cb8446f4274bbc2fbf/
    Complete output (29 lines):
    make: *** No rule to make target '../include/olm/olm.h', needed by 'include/olm/olm.h'.  Stop.

**Comment by tulir** [comment]
the error is saying libolm-dev is missing

**Comment by cbrhaze** [comment]
@tulir but how is it possible if it's installed.
_apt install libolm-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libolm-dev is already the newest version (2.2.2+git20170526.0fd768e+dfsg-1+b11).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded._

I checked all the packages the install or you mentioned. Checked that it uses the correct python versions. Google show nothing relevant) Please help.
