### ISSUE TITLE
Encrypted messages edited in Matrix are prefixed with an Asterisk in Telegram

### ISSUE THREAD

**Issue by s3lph** [tulir/mautrix-telegram#623]
Telegram already marks edited messages as edited. However, if a message in a bridged channel is edited on the Matrix side, for some reason the edited message on the Telegram side now starts with the string `* `, in addition to the `edited` marker (see screenshot below).

## Expected Behavior

![Screenshot of an edited Telegram message](https://user-images.githubusercontent.com/5564491/119871285-94bade80-bf22-11eb-809e-5328021f9561.png)

## Actual Behavior

![Screenshot of an edited Telegram message, with a prepended asterisk](https://user-images.githubusercontent.com/5564491/119871281-94224800-bf22-11eb-81c0-b0e8929a57c8.png)

(Disregard the timestamp difference)

## Steps to Reproduce

1. Set up a bridged channel
2. Write a message in Matrix
3. Look at the sent message in Telegram
3. Edit the message in Matrix
4. Look at the message in Telegram again
5. Note that there's `* ` prepended to the message

**Comment by tulir** [comment]
Seems to work fine for me, is the bridge up to date?

**Comment by s3lph** [comment]
I only recently set the bridge up, `pip install mautrix-telegram[all]==v0.10.0-rc1` in a python3.9 venv.

**Comment by s3lph** [comment]
Config attached: [config.yaml](https://github.com/tulir/mautrix-telegram/files/6556756/config.yaml.txt)

**Comment by JuniorJPDJ** [comment]
What matrix client are you using?
Can you provide message and edit event json from matrix side?

**Comment by s3lph** [comment]
Element on Android.

Original message (decrypted):
```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "Test",
  },
  "room_id": "REDACTED"
}
```

Edit event (also decrypted)
```json
{
  "type": "m.room.message",
  "content": {
    "msgtype": "m.text",
    "body": "* This is a Test",
    "m.relates_to": {
      "rel_type": "m.replace",
      "event_id": "REDACTED",
    },
    "m.new_content": {
      "msgtype": "m.text",
      "body": "This is a Test"
    }
  },
  "room_id": "REDACTED"
}
```

As you can see, the `*` is added by the client in the body (I assume this is a backward compat feature for clients that don't support editing messages), but the text that's supposed to be used is in `m.new_content`. I also saw that there is [code in mautrix-python](https://github.com/tulir/mautrix-python/blob/68940caffa94750370a8e3447eeec7296ca05351/mautrix/types/event/message.py#L404) to handle this, but I didn't (yet) look too closely at the code.
