### ISSUE TITLE
Telegram Puppets in bridged Telegram Channel

### ISSUE THREAD

**Issue by ulpaulpa** [tulir/mautrix-telegram#629]
Currently puppets of users who subscribed to the Telegram channel are invited to the bridged Matrix room. This shouldn't happen, because they aren't public.

If "Sign Messages" is turned on, only the administrators that have the permission to write should be invited, if it is turned off, there should be only one "channel puppet".

For Bridging Messages from Matrix to Telegram, the name should only be included if "Sign Messages" is turned on, and if it is should be suffixed, so it is similar to default message signatures.

**Comment by tulir** [comment]
https://github.com/tulir/mautrix-telegram/blob/master/mautrix_telegram/example-config.yaml#L148-L151

**Comment by ulpaulpa** [comment]
oh. I'm sorry for opening the issue.
