### ISSUE TITLE
typing notifications for myself with double-puppetting

### ISSUE THREAD

**Issue by petabyteboy** [tulir/mautrix-telegram#631]
Happens since upgrading to 0.10.0:

![screenshot2](https://user-images.githubusercontent.com/3250809/122653524-71f8a000-d145-11eb-9dbf-83a7878159d1.png)

**Comment by petabyteboy** [comment]
Reverting https://github.com/tulir/mautrix-telegram/commit/5ed09ad7834c58cca65ef271334c4dc605c778fc resolves the issue, but of course breaks all other telegram->matrix typing notifications as well.

**Comment by olmari** [comment]
I have noticed this behaviour to, for such channels I also see myself joining in as telegram handle, and that is the "person" that is typing etc...

**Comment by petabyteboy** [comment]
Thanks a lot for the quick response! I added the patch and everything works fine now :slightly_smiling_face:
