### ISSUE TITLE
Power level events on room creation require an empty state_key

### ISSUE THREAD

**Issue by phesch** [tulir/mautrix-telegram#640]
According to the Matrix Client-Server API, power level events require a `state_key` that must be an empty string.
Currently, the bridge does not supply it, causing conduit threads to panic when processing room creation requests by the bridge.

This is probably solved by just adding the empty state key to the power level events. Making that change fixed the conduit issue and allowed the bridge to create new rooms on my homeserver.

I'll open a pull request making the change shortly.

**Comment by tulir** [comment]
The Matrix Client-Server API seems to say events in `initial_state` *don't* require a `state_key`

![image](https://user-images.githubusercontent.com/4224639/124909288-f2971780-dff2-11eb-9a27-6f2dc470f791.png)

**Comment by phesch** [comment]
In that case, this may actually be related to the power level event in `initial_state` issue that was encountered in mautrix-signal as well (I can't seem to find it anymore).

**Comment by olmari** [comment]
Well, it does not say "required", but it states on description that it "defaults to empty string" which implies.. that.. While we could argue this being matrix spec deficiency at heart, I do think at this info default empty string would be okay, until "better specs" are defined.

**Comment by phesch** [comment]
I've fixed the issue in conduit causing the panic on room creation (see [conduit issue 116](https://gitlab.com/famedly/conduit/-/issues/116)), so whether `mautrix-telegram` sends the empty `state_key` or not doesn't matter anymore. At this point, whether you want to merge the PR or just close the issue is up to you - sending the empty key might be "friendlier", but omitting it might help discover similar bugs in other homeserver implementations :P .
