### ISSUE TITLE
Support out-of-matrix logging in

### ISSUE THREAD

**Issue by turt2live** [tulir/mautrix-telegram#72]
Particularly for 2FA users, logging in should optionally be done outside of matrix. Ideally Telegram would support oauth2 or something, but failing that a link to a login page can be given to the user trying to log in.

The concern I have is that the password is sent in plain text to the homeserver, so if someone is using a hosted bridge, then the hosting provider has the user's password stored in the synapse database. A login page where the password exchange occurs can help mitigate this problem.

**Comment by tulir** [comment]
Is there some specific API I should implement (widgets?) or should I just add a simple web server for the login?

**Comment by turt2live** [comment]
A simple web server should be fine. With Riot being the only client to support widgets, sending a widget into the room with the webpage wouldn't hurt, but the link would make supporting other clients possible.

The bridge's message could be something like this:
"I've added a widget to this room for you to log in. If you don't see the widget, click here isntead: https://cooldomain.com/login"
