### ISSUE TITLE
Add way to load Telegram history

### ISSUE THREAD

**Issue by tulir** [tulir/mautrix-telegram#99]
Using the appservice client API timestamp parameter (#97). At least when creating portal rooms.

**Comment by skvoter** [comment]
still actual?
can look into it if none work is started on this

**Comment by tulir** [comment]
This is now possible with the `!tg backfill` command. More automatic backfilling might happen later

**Comment by MusiCode1** [comment]
Is there a way to load a telegram channel history?
In channels the `backfill` command is not available.
Thanks.

**Comment by JuniorJPDJ** [comment]
!tg backfill should do the work, I tried it like a year ago ;)
